#!/usr/bin/env node
"use strict";

// sync.js 将仓库内的规则模块拼接后同步到多个 agent 的默认规则文件。
// 跨平台替代 sync.sh，可在 macOS / Linux / Windows 上运行：node sync.js
// 只使用 ES5 语法与最早的 Node 核心 API，兼容 Node 0.10 及以上所有版本。

var fs = require("fs");
var os = require("os");
var path = require("path");

var MODULES = [
  "base.md",
  "tone.md",
  "git.md",
  "lang.md",
  "php.md",
  "go.md",
  "csgo.md"
];

// DELIM 是 AGENT_RULE_TARGETS 的分隔符：Windows 为 ;，macOS/Linux 为 :。
var DELIM = path.delimiter || (process.platform === "win32" ? ";" : ":");

// HOME 解析用户主目录，并为没有 os.homedir 的老版本 Node 提供回退。
var HOME = typeof os.homedir === "function"
  ? os.homedir()
  : (process.env.HOME || process.env.USERPROFILE || "");

var DEFAULT_TARGETS = [
  path.join(HOME, ".codex", "AGENTS.md"),
  path.join(HOME, ".gemini", "GEMINI.md"),
  path.join(HOME, ".claude", "CLAUDE.md"),
  path.join(HOME, ".config", "opencode", "AGENTS.md"),
  path.join(HOME, ".trae-cn", "user_rules", "rule-global.md")
];

// usage 输出命令行参数说明，write 用于选择输出流。
function usage(write) {
  write("Usage: node sync.js [--dry-run] [--list-targets] [-h|--help]");
  write("");
  write("Environment:");
  write("  AGENT_RULE_TARGETS  " + DELIM + "-separated target files. Overrides defaults.");
}

// fileExists 判断路径是否为已存在的普通文件，等价于 bash 的 [ -f ]。
function fileExists(p) {
  try {
    return fs.statSync(p).isFile();
  } catch (e) {
    return false;
  }
}

// pathExists 判断路径是否存在（文件或目录）。
function pathExists(p) {
  try {
    fs.statSync(p);
    return true;
  } catch (e) {
    return false;
  }
}

// mkdirs 逐级递归创建目录，不依赖 Node 10.12+ 的 recursive 选项。
function mkdirs(dir) {
  var parent = path.dirname(dir);

  if (pathExists(dir)) {
    return;
  }
  if (parent !== dir) {
    mkdirs(parent);
  }
  try {
    fs.mkdirSync(dir);
  } catch (e) {
    if (!pathExists(dir)) {
      throw e;
    }
  }
}

// parseArgs 解析命令行参数。
function parseArgs(argv) {
  var opts = { dryRun: false, listTargets: false };
  var i;

  for (i = 0; i < argv.length; i++) {
    if (argv[i] === "--dry-run") {
      opts.dryRun = true;
    } else if (argv[i] === "--list-targets") {
      opts.listTargets = true;
    } else if (argv[i] === "-h" || argv[i] === "--help") {
      usage(console.log);
      process.exit(0);
    } else {
      console.error("Unknown argument: " + argv[i]);
      usage(console.error);
      process.exit(2);
    }
  }

  return opts;
}

// loadTargets 设置本次同步使用的目标文件列表。
function loadTargets() {
  var raw = process.env.AGENT_RULE_TARGETS;
  var targets = [];
  var parts;
  var i;

  if (raw) {
    parts = raw.split(DELIM);
    for (i = 0; i < parts.length; i++) {
      if (parts[i]) {
        targets.push(parts[i]);
      }
    }
    if (targets.length > 0) {
      return targets;
    }
  }

  for (i = 0; i < DEFAULT_TARGETS.length; i++) {
    targets.push(DEFAULT_TARGETS[i]);
  }
  return targets;
}

// buildContent 将所有规则模块拼接为最终提示词内容，模块缺失时返回 null。
function buildContent(dir) {
  var parts = [
    "<!-- Generated by agent-rules/sync.js. Edit source markdown files instead. -->",
    "",
    "# Personal Agent Rules"
  ];
  var i;
  var j;
  var modulePath;
  var lines;
  var kept;

  for (i = 0; i < MODULES.length; i++) {
    modulePath = path.join(dir, MODULES[i]);

    if (!fileExists(modulePath)) {
      console.error("Missing module: " + MODULES[i]);
      return null;
    }

    lines = fs.readFileSync(modulePath, "utf8").replace(/\r\n/g, "\n").split("\n");
    kept = [];
    for (j = 0; j < lines.length; j++) {
      if (!/^<!-- .* -->$/.test(lines[j])) {
        kept.push(lines[j]);
      }
    }

    parts.push("");
    // 剥掉模块首尾的空行，统一由 buildContent 控制段落间为 1 个空行。
    parts.push(kept.join("\n").replace(/^\n+/, "").replace(/\n+$/, ""));
  }

  return parts.join("\n") + "\n";
}

// pad2 把 0-9 的数字补齐为两位字符串。
function pad2(n) {
  return n < 10 ? "0" + n : "" + n;
}

// timestamp 返回与 date +%Y%m%d%H%M%S 一致的本地时间戳。
function timestamp() {
  var d = new Date();

  return "" + d.getFullYear() + pad2(d.getMonth() + 1) + pad2(d.getDate()) +
    pad2(d.getHours()) + pad2(d.getMinutes()) + pad2(d.getSeconds());
}

// writeTarget 原子写入单个目标文件，并在内容变化时创建备份。
function writeTarget(target, content) {
  var existing = null;
  var tmpFile;

  mkdirs(path.dirname(target));

  try {
    existing = fs.readFileSync(target, "utf8");
  } catch (e) {
    // 目标文件尚不存在，视为首次写入。
  }

  if (existing === content) {
    console.log("unchanged " + target);
    return;
  }

  if (existing !== null) {
    fs.writeFileSync(target + ".bak." + timestamp(), fs.readFileSync(target));
  }

  tmpFile = target + ".tmp." + process.pid;
  fs.writeFileSync(tmpFile, content, "utf8");
  fs.renameSync(tmpFile, target);
  console.log("updated " + target);
}

// main 解析参数、生成内容并执行同步。
function main() {
  var opts = parseArgs(process.argv.slice(2));
  var targets = loadTargets();
  var content;
  var i;

  if (opts.listTargets) {
    for (i = 0; i < targets.length; i++) {
      console.log(targets[i]);
    }
    return;
  }

  content = buildContent(__dirname);
  if (content === null) {
    process.exit(1);
  }

  if (opts.dryRun) {
    process.stdout.write(content);
    return;
  }

  for (i = 0; i < targets.length; i++) {
    writeTarget(targets[i], content);
  }
}

main();
