#!/usr/bin/env bash

# sync.sh 将仓库内的规则模块拼接后同步到多个 agent 的默认规则文件。
set -euo pipefail

MODULES=(
  "base.md"
  "tone.md"
  "git.md"
  "php.md"
  "go.md"
  "csgo.md"
)

DEFAULT_TARGETS=(
  "$HOME/.codex/AGENTS.md"
  "$HOME/.gemini/GEMINI.md"
  "$HOME/.claude/CLAUDE.md"
  "$HOME/.config/opencode/AGENTS.md"
  "$HOME/.trae-cn/user_rules/rule-global.md"
)

DRY_RUN=0
LIST_TARGETS=0
CONTENT_FILE=""

# usage 输出命令行参数说明。
usage() {
  printf '%s\n' \
    'Usage: ./sync.sh [--dry-run] [--list-targets] [-h|--help]' \
    '' \
    'Environment:' \
    '  AGENT_RULE_TARGETS  Colon-separated target files. Overrides defaults.'
}

# repo_dir 返回脚本所在仓库目录。
repo_dir() {
  cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

# split_targets 解析用户通过环境变量传入的目标文件列表。
split_targets() {
  local raw_targets=$1
  local old_ifs=$IFS

  IFS=':'
  read -r -a TARGETS <<< "$raw_targets"
  IFS=$old_ifs
}

# load_targets 设置本次同步使用的目标文件。
load_targets() {
  if [[ -n "${AGENT_RULE_TARGETS:-}" ]]; then
    split_targets "$AGENT_RULE_TARGETS"
  else
    TARGETS=("${DEFAULT_TARGETS[@]}")
  fi
}

# cleanup 删除本次运行生成的临时文件。
cleanup() {
  if [[ -n "$CONTENT_FILE" ]]; then
    rm -f "$CONTENT_FILE"
  fi
}

# build_content 将所有规则模块拼接为最终提示词内容。
build_content() {
  local dir=$1
  local module

  printf '%s\n' '<!-- Generated by agent-rules/sync.sh. Edit source markdown files instead. -->'
  printf '\n'
  printf '%s\n' '# Personal Agent Rules'

  for module in "${MODULES[@]}"; do
    local path="$dir/$module"

    if [[ ! -f "$path" ]]; then
      printf 'Missing module: %s\n' "$module" >&2
      return 1
    fi

    printf '\n'
    sed '/^<!-- .* -->$/d' "$path"
  done
}

# write_target 原子写入单个目标文件，并在内容变化时创建备份。
write_target() {
  local target=$1
  local content_file=$2
  local target_dir
  local tmp_file

  target_dir=$(dirname "$target")
  mkdir -p "$target_dir"

  if [[ -f "$target" ]] && cmp -s "$content_file" "$target"; then
    printf 'unchanged %s\n' "$target"
    return
  fi

  if [[ -f "$target" ]]; then
    cp "$target" "$target.bak.$(date +%Y%m%d%H%M%S)"
  fi

  tmp_file="$target.tmp.$$"
  cp "$content_file" "$tmp_file"
  mv "$tmp_file" "$target"
  printf 'updated %s\n' "$target"
}

# main 解析参数、生成内容并执行同步。
main() {
  local dir
  local target

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)
        DRY_RUN=1
        ;;
      --list-targets)
        LIST_TARGETS=1
        ;;
      -h|--help)
        usage
        return
        ;;
      *)
        printf 'Unknown argument: %s\n' "$1" >&2
        usage >&2
        return 2
        ;;
    esac

    shift
  done

  load_targets

  if [[ "$LIST_TARGETS" -eq 1 ]]; then
    printf '%s\n' "${TARGETS[@]}"
    return
  fi

  dir=$(repo_dir)
  CONTENT_FILE=$(mktemp "${TMPDIR:-/tmp}/agent-rules.XXXXXX")
  trap cleanup EXIT

  build_content "$dir" > "$CONTENT_FILE"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    cat "$CONTENT_FILE"
    return
  fi

  for target in "${TARGETS[@]}"; do
    write_target "$target" "$CONTENT_FILE"
  done
}

main "$@"
